debug: False
model_name: downstream_cvae_transfer
max_epochs: 500
num_classes: 3
version_number: 0
epoch_number: 74
chkpt_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/output/classification/downstream_cvae_transfer
output_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/output/classification/downstream_cvae_transfer
dataset: consep_brca
train_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/CoNSeP/TILE_1024_1024_Patch_128_128/MultiClass/combined/Train
val_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/CoNSeP/TILE_1024_1024_Patch_128_128/MultiClass/combined/Valid
test_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/CoNSeP/TILE_1024_1024_Patch_128_128/MultiClass/combined/Test
train_batch_size: 64
val_batch_size: 64
test_batch_size: 64
learning_rate: 0.01
momentum: 0.9


CVAE_MODEL_TRAIN:
  debug: False
  resume_from_checkpoint: False
  model_name: resnet_cvae
  max_epochs: 500
  num_classes: 2
  version_number: 1
  epoch_number: 414
  chkpt_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/output/resnet_cvae/BRCA_synth/checkpoints
  output_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/output/resnet_cvae/BRCA_synth

  dataset: BRCA_synth
  train_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/TCGA_BRCA/CHC_VAE/TILE_1024_1024_Patch_128_128/synthetic/Train
  val_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/TCGA_BRCA/CHC_VAE/TILE_1024_1024_Patch_128_128/real/Test
  test_dir: /ocean/projects/asc130006p/shared/mahmudul/Uncertainty_Estimation/data/segmentation/TCGA_BRCA/CHC_VAE/TILE_1024_1024_Patch_128_128/real/Valid

  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32
  learning_rate: 0.001
  model_parameters:
    background_disentanglement_penalty: 10
    salient_disentanglement_penalty: 10
    salient_latent_size: 128
    background_latent_size: 128